export const FORM_CHANGE = "CAMBIO_EL_FORMULARIO";

export const SEARCH_CHANGE = "CAMBIO_EL_SEARCH";

export const SEARCH_CLICK = "EL_SEARCH_FUE_CLICKEADO";

export const CATEGORIES_LOAD = "CARGARON_LAS_CATEGORIAS";

export const PRODUCTS_LOAD = "CARGARON_LOS_PRODUCTOS";

export const ORDERS_LOAD = "CARGARON_LAS_ORDENES";

export const ADD_CARRITO = "ADD_CARRITO";