export const FORM_CHANGE = "CAMBIO_EL_FORMULARIO";

export const SEARCH_CHANGE = "CAMBIO_EL_SEARCH";

export const CATEGORIES_LOAD = "CARGARON_LAS_CATEGORIAS";

export const PRODUCTS_LOAD = "CARGARON_LOS_PRODUCTOS";