export const FORM_CHANGE = "CAMBIO_EL_FORMULARIO";

export const SEARCH_CHANGE = "CAMBIO_EL_SEARCH";

export const SEARCH_CLICK = "EL_SEARCH_FUE_CLICKEADO";

export const CATEGORIES_LOAD = "CARGARON_LAS_CATEGORIAS";

export const PRODUCTS_LOAD = "CARGARON_LOS_PRODUCTOS";

export const ORDERS_LOAD = "CARGARON_LAS_ORDENES";

export const ADD_CARRITO = "ADD_CARRITO";

export const CHANGE_USER_STATUS = "CAMBIAR_ESTADO_DE_USUARIO";

export const CHANGE_EDIT_PRODUCT = "CAMBIAR_ESTADO_DE_PRODUCTO_A_EDITAR";

export const SET_USER = "SETEA_USER";

export const CATEGORIES_FILTER = "CATEGORIES_FILTER"